= Documentation

The project documentation is written with AsciiDoc (source in the `src/docsrc` folder).
If you want to modify and rebuild the documentation, install Asciidoctor and
a couple of supporting gems for PDF and diagrams.

*For Debian-based systems:*

```
sudo apt install ruby
sudo gem install asciidoctor asciidoctor-diagram asciidoctor-pdf asciidoctor-diagram-plantuml
```

(In this Documentation section,
for Fedora systems the commands are the same, but replacing `apt` with `dnf`.)

== Building the documentation

To build the documentation, navigate to the `src/docsrc` directory and run:

```
./docbuild.sh all
```


== Diagram support

For diagrams, some additional packages are required.

```
sudo apt install graphviz
```

For mermaid, rather than use `mermaid-cli` from the package manager,
I wanted the latest version of mermaid-cli via npm
(after installing nvm for the latest version of nodejs).

To install `nvm` and `node`:
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
source ~/.bashrc || source ~/.zshrc
nvm install --lts
```

To install Mermaid:
```
npm install -g @mermaid-js/mermaid-cli
```

.An unsuccessful tangent
****
I like Baraa's specifications table but didn't want to copy it into Asciidoc,
so I thought I might extract the text from his image and reformat it into
Asciidoc. I ended up letting AI have at it.

OCR image text extraction support::
+
For OCR image text extraction, Tesseract and the Python Pillow and pytesseract libraries are required.
+
```
sudo apt install tesseract-ocr
pip install Pillow pytesseract
```
+
On Fedora, the package is called `tesseract`.

Preparing the specifications table::
+
1.  Extract the text:
    
    pushd src/docsrc/img-extract
    python ocr-extract.py > ocr-output.txt
    popd
+
2.  _..._
+
3.  Okay, nevermind. I let ChatGPT have at it and do it all for me.
    I uploaded the image and gave it this prompt:
+
    I will upload an image that is basically a fancy table.
    Extract the text from the image and convert it to a table in AsciiDoc.
    Let me know when you're ready.

But the OCR was a good exercise anyway.

****

=== Preparing the ETL mindmap

Let's try ChatGPT again.

Well done, ChatGPT! Here's the prompt and you can find the source image in this repository
under `src/docsrc/img-extract/etl-map.png`.

    New task: Now I'm going to upload an image of a fancy mindmap diagram.
    I'd like you to extract the information from the image and recreate it
    using mermaid syntax. Let me know when you're ready.

I'll clean it up with colors and flags myself.
Can't let AI rob me of all the fun!

(I later asked ChatGPT to convert to a Drawio file instead, but it had an error about
IDs. After debugging with `xmllint` and fixing the IDs, I got a valid Drawio file,
but it was only two node levels deep and didn't follow the style anyway. So, I'm
sticking with mermaid.)
